### ISSUE TITLE
Please add code folding (collapse/hide functions)

### ISSUE THREAD

**Issue by RichardGG** [pebble/cloudpebble#105]
http://en.wikipedia.org/wiki/Code_folding

![image](https://cloud.githubusercontent.com/assets/5629162/4400947/8a1e2008-4487-11e4-82eb-540db97f17cb.png)

I'm not sure how complicated/feasible this is to add, but it would be very useful.
As I get more and more functions in my code it starts to become a pain to manage.

**Comment by kamotswind** [comment]
The latest version seems to have this feature. I think this can be closed.

**Comment by Spacerat** [comment]
Yep! See: #162
