### ISSUE TITLE
Confguration URL is malformed after return_to parameter is added

### ISSUE THREAD

**Issue by netgio** [pebble/cloudpebble#124]
The URL generated by the emulator to launch a the configuration URL results in a malformed URL due to an error in the handling of anchors (#'s) for config settings and query string params.

this results in config URLs with anchors duplicated before the query param, which the browser will truncate. for example I see this in the config window address bar:
`https://my.config.host/login#%7B%22access-token%22%3A%22some-token%22%7D?return_to=https%3A//cloudpebble.net/ide/emulator/config%3F#%7B%22access-token%22%3A%22some-token%22%7D`

What I should see is:
`https://my.config.host/login?return_to=https%3A//cloudpebble.net/ide/emulator/config%3F#%7B%22access-token%22%3A%22some-token%22%7D`

Looking at libpebble.js the issue seems to be that the URL splitting/joining code does not account for a configuration URL that contains anchors AND it SEEMS (I cannot confirm) that the way the URL is stored and packed/unpacked it includes any config settings as anchors... so I THINK the code in libpebble.js to handle adding the "return_to" param starts by getting a URL that looks like:
`<config url>#<JSON formatted config data>`

My proposed fix handle_config_message() is:
```javascript
    /// existing code to fetch and unpack the config URL...then...
    var hash_parts = url.split('#');
    var query_parts = url.split('?');
    console.log(hash_parts, query_parts);
    // note that query_parts[0] will include the hashes if there were no query params
    // if there were query params, the hashes will still be on the end of the last param in query_params
    if (query_parts.length == 2) // there were query params
    {
      //we need to strip the hash parts from the last param if they existed.
      //we do this before testing for length == 1 because that code pushes an empty string into the array making the length == 2 anyway
      var query_string = query_parts[1].split('#');
      console.log('the query and the hashes: ' + query_string);
      // make the query string JUST the query params... leave the hashes to be added separately.
      query_parts[1] = query_string[0];
    }
    if(query_parts.length == 1) {
      //get the base url by getting rid of the hash_parts
      var base_url = query_parts[0].split('#');
      console.log("base =" + base_url[0]);
      // we use query_parts to rebuild the new URL so set the first part to the clean base URL
      query_parts[0] = base_url[0];
      query_parts.push('');
    }

/// no changes to current code past this point...
    if(query_parts[1] != '') {
      query_parts[1] += '&';
    }
    

    query_parts[1] += 'return_to=' + encodeURIComponent('http' + '//' + 'location.host' + '/ide/emulator/config?');
    var new_url = query_parts.join('?');
    if(hash_parts.length > 1) {
      new_url += '#' + hash_parts[1];
    }
    console.log("new url: " + new_url);
```

**Comment by cpfair** [comment]
:+1: 

My app attempts to open

    https://pebbleauth.cpfx.ca/config.html?ver=1.1.0#[]

and instead I end up getting sent to 

    https://pebbleauth.cpfx.ca/%5B%5D&return_to=https%3A//cloudpebble.net/ide/emulator/config%3F

**Comment by sarfata** [comment]
For Pebble internal tracking purposes: https://pebbletechnology.atlassian.net/browse/PBL-17813
