### ISSUE TITLE
Doesn't import worker_src from zip/github

### ISSUE THREAD

**Issue by MarSoft** [pebble/cloudpebble#125]
When I try to import my project containing a background worker from either ZIP archive or GitHub repo, CloudPebble ignores worker completely.
Steps to reproduce:
- create a project with background worker (either on CloudPebble or with native SDK)
- compress/export it to ZIP archive
- import it to CloudPebble

Expected results: all source files are imported
Actual results: everything related to background worker (all files from /worker_src dir) are missing.

**Comment by Spacerat** [comment]
Fixed by #256
