### ISSUE TITLE
Importing 3.0 projects with ~bw / ~color resources fails

### ISSUE THREAD

**Issue by ccharles** [pebble/cloudpebble#133]
I just tried importing a project that's working well with version 3.0-dp3 of the native SDK into CloudPebble. My project uses [per-platform resources](http://developer.getpebble.com/guides/pebble-apps/resources/image-resources/#specifying-resources-per-platform):

> When packing resources into a Pebble project, the SDK will look for any files with special suffixes and use those in preference to those without. The suffixes `~color` and `~bw` are currently supported. If one of these files is found, it will be used instead of any other matching file name without the suffix for platforms that support those colors.

CloudPebble doesn't seem to support this, as I received the following error when importing:

> Error: "There is no item named u'resources/dial_base.png' in the archive"

It's correct that there is no `resources/dial_base.png`, but there *is* a file called `dial_base~bw.png` in the `resources/` directory that should get picked up for Aplite instead.

My project is currently configured to build only for Aplite, but I also tested an archive that provides `dial-base~color.png` as well so that both platform-specific files exist, which generated the same error message.

**Comment by btmi** [comment]
I can confirm this problem.  It appears that while color and B&W bitmap resources are saved to the zip file, the color resources are discarded when importing into a new project and so all bitmap resources must be added again manually.
