### ISSUE TITLE
Installing app modal does not go away when emulator shows failes

### ISSUE THREAD

**Issue by quillford** [pebble/cloudpebble#148]
![cloudpebble_ _octoface](https://cloud.githubusercontent.com/assets/8762862/7626895/052565fc-f9c5-11e4-8cd8-cae5f2df9c36.png)

**Comment by quillford** [comment]
Eventually it recognized that it failed, but it took awhile.

**Comment by Katharine** [comment]
This is the distinction between the *watch* knowing that it failed and the *phone* knowing that it failed.

**Comment by quillford** [comment]
ah
