### ISSUE TITLE
Unable to install any app/watchface to aplite emulator

### ISSUE THREAD

**Issue by PanicMan** [pebble/cloudpebble#150]
Every time I get the error: Installation rejected. Try rebooting the emulator and trying again. rebooting the Emulator does not help. Does not matter what SDK I'm using. Installation on a real Pebble (not Time) is working.

**Comment by unwiredben** [comment]
Is this still a problem for you?  If not, please close the issue.

**Comment by PanicMan** [comment]
Yes, it is, but the problem is different now, the emulator starts, but the installation hangs on "authenticating". After some seconds the emulator close itself, the message with "authenticating" stay forever...

**Comment by kamotswind** [comment]
I am actually getting the same issue with the "Authenticating..." hanging after the emulator is booted and functional (minus the watchface). This was working several days ago just fine. If I click around a bit on the screen, I can get the message to go away and it is replaced with "Waiting for phone. Make sure the developer connection is enabled." So it seems like the button to install it on the emulator boots the emulator properly but then runs the code for installing to the phone.

**Comment by ibennani** [comment]
When this happens to me, I just click on the wheel at the right under the Pebble emulator window. Then tap the big red "Shut down" button. Finally tap the green play arrow at the upper right corner of the browser window and compile your project again.

Hope this helps!

**Comment by PanicMan** [comment]
In recent time everything works fine, so I close the issue... Thanks a lot!
