### ISSUE TITLE
Secondary font created based on the same resource is not imported from Github

### ISSUE THREAD

**Issue by ygalanter** [pebble/cloudpebble#174]
Added a TTF resource, created 2 fonts based on it i.e. MYFONT_30 & MYFONT_18, pushed commit to GitHub. When reimported as new project - only MYFONT_30 got created.

**Comment by cpboyd** [comment]
This is true of any import (ZIP upload included)

I just exported and imported a project (because I couldn't update image resources easily)

**Comment by Spacerat** [comment]
The beta pretty much fixed this. It is now possible to import multiple font IDs, so I'm going to close this.
