### ISSUE TITLE
Github commit doesn't honor added color resources

### ISSUE THREAD

**Issue by ygalanter** [pebble/cloudpebble#177]
Added color image to an existing generic counterpart. Pushed commit, CP reported "nothing to commit"

**Comment by jira-sync** [comment]
| ![](https://pebbletechnology.atlassian.net/secure/useravatar?size=xsmall&ownerId=jonb&avatarId=13800)&nbsp;**Jon Barlow** commented: |
|:---------------------------|

Devsupport:

I just enabled a Chalk build on an existing project, attempted to commit and got same error as before “Nothing to commit.”

-------------------

1. Had watchface made in cloudpebble commited to github. 
2. Accidentally had the type set to "Watchapp". Switched to "Watchface". 
3. Attempted to create a new commit to github to push the updated 
appinfo.json, messages comes up with "Nothing to commit".
