### ISSUE TITLE
SDK 3.2 apps don't run on 3.1

### ISSUE THREAD

**Issue by expando** [pebble/cloudpebble#189]
I tweaked an old Pebble app to change the color only and after compiling with CloudPebble a few days ago, it no longer worked on my Pebble Time. I didn't change any code except the color name. The only reason I can find is that firmware 3.2 came out but my watch is still on 3.1. I currently cannot upgrade my watch to 3.2 because of a constant crashing bug in 3.2.

**Comment by unwiredben** [comment]
This is an intentional change in the SDK, from what I've read, so I don't think a fix in CloudPebble is likely. :(

**Comment by expando** [comment]
Could an option be added to CloudPebble to allow apps to be compiled against 3.1 for now until the crashing is fixed?

**Comment by Katharine** [comment]
What crashing issue? I'm not aware of one.

Only running on 3.2 is by design; I have no present intention to change it.

**Comment by expando** [comment]
3.2 crashes occasionally after installing language packs.

Before 3.2, Pebble Time communities in Asia have been evangelizing the use of language packs for the Pebble Time.

In particular, Pebble Japan (active on the Pebble Japan Google Plus page) and Pebble Hong Kong (active on the Pebble Hong Kong Facebook group) have developed their own local interest groups to promote the Pebble Time and are teaching people how to use the language packs to make the Pebble Time work.

After 3.2, there have been complaints about the crashing and new users are claiming to be mislead by those communities. Now the forums are teaching people how to downgrade to 3.1.

**Comment by Katharine** [comment]
Language packs are not yet supported by any version of 3.x, and being installable at all is an oversight.

We cannot prioritise "fixing" this; nor is it possible to add backwards compatibility. Pebble users are expected to always upgrade when new firmware is released.

**Comment by expando** [comment]
It's unfortunate the cat was let out of the bag. How do we contain this?
