### ISSUE TITLE
JS "Promise" object not working in the emulator

### ISSUE THREAD

**Issue by mp2323** [pebble/cloudpebble#200]
While using "Promise" on the phone works perfectly fine, however, trying to access it within the emulator results in an error thrown: 
**[PHONE] pebble-app.js:?: ReferenceError: Promise is not defined**

**Comment by Katharine** [comment]
A built-in `Promise` object is not part of the PebbleKit JS API. This is intentionally unsupported, and you should not use it if you wish to be certain of broad compatibility across phones.
