### ISSUE TITLE
Pressing "Z","X" or "Y" sometimes triggers multiple tap events

### ISSUE THREAD

**Issue by marcpabst** [pebble/cloudpebble#201]
Happens in both Basalt and Aplite. This is really annoying when you are listening for just a single tap. You can temporarily fix this by reloading the page, so this may not be top priority.

**Comment by mp2323** [comment]
Workaround: Call one of the functions below  to manually trigger **just one** tap event. 
```javascript 
SharedPebble.getPebble().done(function(pebble) {pebble.emu_tap("X", 0);});
SharedPebble.getPebble().done(function(pebble) {pebble.emu_tap("Y", 0);});
SharedPebble.getPebble().done(function(pebble) {pebble.emu_tap("Z", 0);});
```

**Comment by marcpabst** [comment]
Not really important anymore...
