### ISSUE TITLE
Emulator fails to run JS code containing special characters

### ISSUE THREAD

**Issue by marcpabst** [pebble/cloudpebble#202]
Strangely, the emulator fails to run JS code that contains special characters like "°","ä" or "ß" within any strings. It just quietly dies.  It will also fail when you write the characters like this: "\u00B0".
However, both ways seem to work fine on Android phones.

**Comment by cpboyd** [comment]
I'll add that I've tested this on both beta.cloudpebble.net and the normal site.
The Basalt emulator never seems to actually receive a message from the phone-app.js emulator if it contains a unicode character.

I only get this error on the normal site, though:
[PHONE] pebble-app.js:?: [PHONESIM] [WARNING] Exception decoding QemuInboundPacket.footer

**Comment by marcpabst** [comment]
Not really important anymore...
