### ISSUE TITLE
Imported projects with multiple font size resources pointing to the same TTF do not work

### ISSUE THREAD

**Issue by dcormier** [pebble/cloudpebble#210]
After importing a project with [this `appinfo.json`](https://github.com/dcormier/beam-up/blob/c6130020d04dff728976619121a780e7f5d8c6de/appinfo.json) file, I get this error while compiling:

`../src/main.c:217:98: error: 'RESOURCE_ID_FONT_IMAGINE_48' undeclared (first use in this function)`

The thing is, it *is* declared in the `appinfo.json` file. After some digging around, it seems that CloudPebble doesn't handle two resource entries pointing at the same file. In this case it was done to use the same font at two different sizes.

This is pretty painful as this is what Pebble is pushing for Windows development, but it doesn't support features (like this and #151) that are in use by projects we might like to fork/contribute to.

**Comment by orviwan** [comment]
I had the same issue.

```javascript
{
    "resources": {
        "media": [
            {
                "characterRegex": "[:0-9]",
                "file": "fonts/DS-Digital-Bold.ttf",
                "name": "FONT_DIGITALE_71",
                "type": "font"
            },
            {
                "characterRegex": "[:0-9]",
                "file": "fonts/DS-Digital-Bold.ttf",
                "name": "FONT_DIGITALE_56",
                "type": "font"
            },
            {
                "characterRegex": "[:0-9A-Z ]",
                "file": "fonts/DS-Digital-Bold.ttf",
                "name": "FONT_DIGITALE_22",
                "type": "font"
            }
        ]
    }
}
```

**Comment by Spacerat** [comment]
Yep, the import code only supports filename-->ID many-->one relationships at the moment; I've put fixing this on my to-do list.

However, CloudPebble's backend and UI does actually support what you're trying to do, so if you'd like a workaround for now, you can use the "Another Font" button for the font resource and add the new identifier back. (If you do that and then export the project you'll see that the resulting appinfo.json probably looks like the one you're not able to import!).

**Comment by Spacerat** [comment]
This has been fixed as part of the upcoming support for Pebble Time Round, with an updated interface for configuring fonts to support multiple resource IDs and multiple variants with different tags. Importing of a appinfo.json file like the one you've given above should work fine now, but only for fonts, and you can't specify different targetPlatforms for each ID!  

You can try the new features out on the [CloudPebble Beta](https://beta.cloudpebble.net/ide/) if you like. If you do, let me know if you have any issues!

**Comment by Spacerat** [comment]
Closing this since (I just realised) it duplicates #174
