### ISSUE TITLE
Adding new resources causes cloudpebble to not fully write the image name to appinfo.json

### ISSUE THREAD

**Issue by dombeef** [pebble/cloudpebble#212]
This just started today(Although I havent uploaded anything in weeks) where when I try to upload an image, it gives an error when I try to compile, and when I look at the appinfo.json from the downloaded zip, it shows the image file as the name minus the last digit.

Ex: I upload a file called num_cond_cloudy.png, and cloudpebble gives an error when I compile, I check appinfo.json, and instead of num_cond_cloudy.png, it thinks it is num_cond_cloud.png.

No matter what I do(even editing appinfo.json, and then importing the zip to cloudpebble), I cant seem to fix this issue, the new images I upload always seem to have the one letter removed from their file name. The older images I uploaded months ago have no issue, even after I import it again.

To recreate this issue:
1. Upload a PNG image and have it linked to the project so your watchface is dependent on the image
2. Try to compile and see that cloudpebble gives an error like "No resource found at resources/images/num_cond_cloud.png for basalt"
3. Download the zip for the project and notice that the file appinfo.json proves that the last digit of the file is removed.

Any help? I was literally on the last part of finishing up my watchface and I have no idea why this randomly started happening, and that no one else appears to have the issue.

**Comment by Spacerat** [comment]
The error was in the code which generates appinfo.json files from your project database, which should get fixed in #213. Until that's deployed, if you're in a rush, the best workaround I can suggest is to download the project and build it with the SDK.

**Comment by dombeef** [comment]
Oh awesome, thanks for the info! And yeah, I'll just wait until it's updated on the server.
