### ISSUE TITLE
Can't easily update image resources

### ISSUE THREAD

**Issue by cpboyd** [pebble/cloudpebble#214]
Currently, it's easier to export as a zip, replace the image files, and import again.
(Except for having to re-add various font sizes after import. See issue #174)

If you try to simply re-upload an image, it gives you the "a resource with this name already exists".

There should certainly be a way to re-upload image resources, especially when you're trying to get the colors just right.

**Comment by Spacerat** [comment]
The resources interface has been updated for Pebble Time Round (961ee35ec7f0b651cbdaaaba260fc213b8c1ac07) where it is now possible to delete and re-upload variants of resources and also rename them. You can try the new features out here https://beta.cloudpebble.net/ide/ , let me know if you have any issues!

**Comment by Spacerat** [comment]
The beta has been merged and deployed, so this is done!
