### ISSUE TITLE
Cloudpebble file upload is broken since last update

### ISSUE THREAD

**Issue by n3v3r001** [pebble/cloudpebble#228]
Hey there!

Since the last update 2-3 days ago we cant upload files to cloudpebble.
I asked in forum if this problem is just for me or for all users - it looks like this is to all users -> so its a bug.
https://forums.getpebble.com/discussion/29326/cloudpebble-file-upload-offline?new=1

@Cloudpebble Team: Please repair the file upload feature in cloudpebble.

Thanks!

**Comment by n3v3r001** [comment]
Hi there!

Thanks, now you added the Upload Button to the "Upload new Ressource".
But its still missing on the old ressources - to upload a new file for an existing ressource.

@Cloudpebble Team: Please also repar the file upload feature in the existing ressources!

Thanks!

**Comment by Spacerat** [comment]
Hi @n3v3r001 , is #232 what you're asking for? This change has been merged should be deployed within a few days.

**Comment by n3v3r001** [comment]
I mean, the "upload new file for an existing ressource is still missing since last update.

(Look in the screenshot, i cant replace the image currently)
![image](https://cloud.githubusercontent.com/assets/7279949/10658444/2490bed6-7897-11e5-9e8a-4a12d9ceb6b3.png)

**Comment by Spacerat** [comment]
You can't add multiple files for nn SDK 2 resource, it can only have one file. If you had multiple versions of the file, which version would your project use when you reference PNG_BIGDIGIT_0?

**Comment by n3v3r001** [comment]
I just want to replace the file with a new one - this worked proberbly unitl the last update.
Now the upload button is missing - i cant replace the file

(workaround is to delete the file and upload a new ressource, but this is very cumbersome, because i also need to enter the identifier  and so on..)

**Comment by Spacerat** [comment]
Ah yes, OK. As I said before, this feature will return the next time that CloudPebble is deployed. I'll let you know when that happens!

**Comment by Spacerat** [comment]
@n3v3r001 the branch has been deployed now, so you should be able to replace files. Does that fix your problem?

**Comment by n3v3r001** [comment]
Yes it works, thanks :)
