### ISSUE TITLE
If minor version starts with 0 it is treated as an octal number

### ISSUE THREAD

**Issue by ygalanter** [pebble/cloudpebble#237]
If app has minor version starting with 0, it is treated as an octal number and anything over x.07 (e.g. 1.08 or 1.09) causes compile-time error similar to:

    chalk/appinfo.auto.c:8:27: error: invalid digit "8" in octal constant
    chalk/appinfo.auto.c:8:3: error: missing initializer [-Werror=missing-field-initializers]
    chalk/appinfo.auto.c:8:3: error: (near initialization for '__pbl_app_info.process_version.minor') [-Werror=missing-field-initializers]

**Comment by Katharine** [comment]
This is not a cloudpebble bug, except in as much as cloudpebble should prevent you doing that. 

Never use leading zeroes in pebble app version numbers, they don't behave.

**Comment by ygalanter** [comment]
Was not aware of this. Will avoid in the future, thanks.
