### ISSUE TITLE
Runs Chalk if no emulator running when coding a Pebble.js project

### ISSUE THREAD

**Issue by CWFranklin** [pebble/cloudpebble#241]
Seems redundant running Chalk emulator by default if the app isn't (and in this case, can't be) built for that platform.

**Comment by Spacerat** [comment]
Good spot. Basalt should be the default platform - I've submitted #242 to fix this.

**Comment by CWFranklin** [comment]
Just realised that the Run button (before it's clicked for the first time) says that it builds for Chalk which it doesn't. It says it will run on the Chalk emulator as well which with your change, it shouldn't.

![chalkissue](https://cloud.githubusercontent.com/assets/3866304/11125748/8134bb7e-8963-11e5-9b57-d56bb32ff455.png)

As a side note, it would be nice to be able to specify which platforms the app is built for as I would have been happy not supporting Aplite at all.

**Comment by Spacerat** [comment]
Another good spot! I'll get back to you on all of that.

**Comment by Spacerat** [comment]
Fixed by #244
