### ISSUE TITLE
Incorrect warning when formatting int32_t with %ld

### ISSUE THREAD

**Issue by ogerardin** [pebble/cloudpebble#262]
I have the following code:

```C
        int32_t capacity = dict_find(iter, KEY_CAPACITY)->value->int32;
        int32_t occupancy = dict_find(iter, KEY_OCCUPANCY)->value->int32;
        APP_LOG(APP_LOG_LEVEL_DEBUG, "parking status received: capacity=%ld, occupancy=%ld", capacity, occupancy);
```

The editor complains that 
> format specifies the type 'long' but argument has type 'int32_t'

However, it compiles OK.

In the contrary, if I change %ld to %d as the warning suggests, compilation fails with error: 
> error: format '%d' expects argument of type 'int', but argument 5 has type 'int32_t' [-Werror=format]

**Comment by bradtgmurray** [comment]
You need to use the PRI* macros defined in <inttypes.h> to print fixed width types.

```
        APP_LOG(APP_LOG_LEVEL_DEBUG, "parking status received: capacity=%"PRId32", occupancy=%"PRId32, capacity, occupancy);
```

For more information, see http://stackoverflow.com/questions/12120426/how-to-print-uint32-t-and-uint16-t-variables-value

**Comment by ogerardin** [comment]
Thanks, I didn't know that.
Maybe the editor warning could point in this direction ?

**Comment by unwiredben** [comment]
That warning comes from GCC, and at the point in compiling where it's complaining, it's already translated the type from the stdint.h typedef to the full type and lost the information to give you a better message.
