### ISSUE TITLE
Support pushing builds to Pebble appstore

### ISSUE THREAD

**Issue by matthewtole** [pebble/cloudpebble#30]
Now that the CloudPebble authentication system has been replaced with the Pebble SSO, I would like to see the ability to push (successful) builds of apps to the Pebble appstore. This would require:
1. Associating a CloudPebble project with a PAS item.
2. Pebble providing an API for creating a new release of an app.
3. CloudPebble having an area to enter release notes.

**Comment by PanicMan** [comment]
:thumbsup:
