### ISSUE TITLE
Can't push to Github repository where im collaborator

### ISSUE THREAD

**Issue by klmz** [pebble/cloudpebble#44]
I am trying to communicate with a public repo where I'm only collaborator with full access, so not the owner. CloudPebble has the following behaviour:
- Push new commit ends with  Error: no error
- Pull new commit ends with Error: No GitHub repo defined.
- Github settings I saved are not persisted, they disappear when I reload the website.

Is this an issue with CloudPebble or Github?

**Comment by ziplizard** [comment]
How does one re-authenticate from the command line?

**Comment by funkycadet** [comment]
@ziplizard You can use GitHub CLI for that
